name: "Chromatic"
on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn install
      - uses: chromaui/action@releases/v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          appCode: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}